name: Deploy Vite React to AWS EC2

on:
  push:
    branches:
      - main  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Copy build to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  # or ec2-user depending on AMI
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          source: "dist/*"
          target: "~/vite-app"

      - name: SSH and Serve App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          script: |
            cd ~/vite-app
            nohup serve -s . -l 3000 > app.log 2>&1 &
